### ISSUE TITLE
Unsupported OS X version 10.14. Krypton requires 10.11+

### ISSUE THREAD

**Issue by tiernano** [kryptco/kr#211]
WAY EARLY, i know, but not been mentioned yet... Just installed the dev preview of macOS 10.14, and getting the following error when trying to re-install:

`Unsupported OS X version 10.14. Krypton requires 10.11+`

I had it installed on 10.13, and when trying to login somewhere, i get the following:

`dlopen /usr/local/lib/kr-pkcs11.so failed: dlopen(/usr/local/lib/kr-pkcs11.so, 2): no suitable image found.  Did find:
	/usr/local/lib/kr-pkcs11.so: code signing blocked mmap() of '/usr/local/lib/kr-pkcs11.so'
	/usr/local/lib/kr-pkcs11.so: stat() failed with errno=38`

I know its very early days, but sticking this up as a heads up...

Thanks.

**Comment by kcking** [comment]
Thank you for reporting this. As we setup our build system for 10.14, you can fix a currently installed version by changing the `PKCS11Provider` line added by Krypton in your config to 

```IdentityAgent ~/.kr/krd-agent.sock```

Let us know if that helps!

**Comment by tiernano** [comment]
yea, that fixes the problem alright! Thanks!

**Comment by bassrock** [comment]
Confirmed that fixed mine as well.

**Comment by kcking** [comment]
This has been fixed with kr `2.4.10` which has just been released. Thanks again for reporting!

**Comment by huw** [comment]
I'm still seeing this error on macOS Mojave and Krypt 2.4.10, even after `brew reinstall kr`. To be clear, I see this in my terminal:

<img width="879" alt="screen shot 2018-07-18 at 12 04 31 pm" src="https://user-images.githubusercontent.com/2456132/42855217-ca60a9b6-8a82-11e8-8bab-49eeb0b17391.png">

The existing workaround still works correctly.
